### ISSUE TITLE
Putting an object to a local endpoint

### ISSUE THREAD

**Issue by akubisch** [samoconnor/AWSS3.jl#26] opened 2018-03-27 13:24 UTC
Hi!

I'm unfortunately having some trouble with a local endpoint we're using here. This is what I tried:
```julia
aws = AWSCore.aws_config(creds = AWSCore.AWSCredentials("XXXXXXXXXXX",
                                        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"),
                endpoint = "https://s3.my.local.endpoint.de")

s3_create_bucket(aws, "test.bucket")

s3_list_buckets(aws) # works well, shows me "test.bucket"

s3_put(aws, "test.bucket", "testkey", "Hello!") # fails
```
The error message I get is:
```julia
IOError(EOFError() during request(https://s3.my.local.endpoint.de/test.bucket/testkey))
in s3_put at AWSS3/src/AWSS3.jl:619
in s3_put at AWSS3/src/AWSS3.jl:619
in #s3_put#27 at AWSS3/src/AWSS3.jl:651
in  at base/<missing>
in #s3#1 at AWSS3/src/AWSS3.jl:81
in macro expansion at Retry/src/repeat_try.jl:206 
in macro expansion at AWSS3/src/AWSS3.jl:107 
in do_request at AWSCore/src/AWSCore.jl:399
in macro expansion at Retry/src/repeat_try.jl:206 
in macro expansion at AWSCore/src/AWSCore.jl:421 
in http_request at AWSCore/src/http.jl:22
in macro expansion at Retry/src/repeat_try.jl:206 
in macro expansion at AWSCore/src/http.jl:31 
in  at base/<missing>
in #request#1 at HTTP/src/MessageRequest.jl:44
in  at base/<missing>
in #request#1 at HTTP/src/ExceptionRequest.jl:19
in  at base/<missing>
in #request#1 at HTTP/src/ConnectionRequest.jl:32
in  at base/<missing>
in #request#1 at HTTP/src/StreamRequest.jl:53
in macro expansion at base/task.jl:302 
in macro expansion at HTTP/src/StreamRequest.jl:57 
in startread at HTTP/src/Streams.jl:146
in readheaders at HTTP/src/Messages.jl:468
in readuntil at HTTP/src/IOExtras.jl:171
```

It looks like the package is using path-style buckets, while our endpoint uses DNS-style buckets. Is that something that could easily be changed? Or might the problem be something else?

Any help is appreciated :-) Thanks a lot!

**Comment by samoconnor** [comment] 2018-03-28 00:04
According to the spec, all S3 endpoints support both types of request: 
[_"When making requests by using the REST API, you can use virtual hosted–style or path-style URIs for the Amazon S3 endpoints."_](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAPI.html)

AWSS3.jl always makes path-style requests.

Is your local endpoint an S3 endpoint? or is it a 3rd party emulation of some sort? 

Perhaps you can use HTTP.jl to construct a PUT request that your endpoint will accept. There is an example in the HTTP.jl test suite of doing PUT to S3 without using AWSS3.jl or AWSCore.jl: https://github.com/JuliaWeb/HTTP.jl/blob/master/test/async.jl#L125-L126

**Comment by akubisch** [comment] 2018-03-28 13:03
Okay, I just got the information that our endpoint does indeed accept both types of request. In fact, given our endpoint server logs, the julia put request does not even reach the server. I also tested getting an object, which works fine. It seems that there might be some bug hidden somewhere here...

**Comment by samoconnor** [comment] 2018-03-29 00:04
If you check out the latest master of AWSCore.jl https://github.com/JuliaCloud/AWSCore.jl/commit/48b88ec81707c76d7894ebc843eecbca389b5ec2, 
and do `AWSCore.set_debug_level(4)`,
you should get a log of what was sent and received on the network. Hopefully this helps to figure out what is going wrong.

**Comment by akubisch** [comment] 2018-03-29 08:43
Okay, I've found the problem (in general, not in detail). Good news: It is not AWSS3.jl, but HTTP. S3 upload functions flawlessly when pinning HTTP to 0.6.4 - I hope this information will help you in finding out the actual problem :-)

**Comment by samoconnor** [comment] 2018-03-30 01:30
Thanks for the update @akubisch.

Can you tell me does it work with any of HTTP v0.6.5?, v0.6.6? or v0.6.7?

Can you please post the output of doing the PUT using latest AWSCore master with `AWSCore.set_debug_level(4)` and, in `HTTP.jl/src/HTTP.jl` set `DEBUG_LEVEL=2`

**Comment by akubisch** [comment] 2018-04-03 06:58
Okay, so it works up to HTTP v0.6.5, since 0.6.6 it doesn't. I created the output you wanted using 0.6.6:

```julia
canonical_form:
PUT
/mybucket/testkey

content-md5:lS0sVtBIWVgzZ0e83ZhZDQ==
content-type:application/octet-stream
host:s3.my.local.endpoint.de
user-agent:AWSCore.jl/0.0.0
x-amz-content-sha256:334d016f755cd6dc58c53a86e183882f8ec14f52fb05345887c8a5edd42c87b7
x-amz-date:20180403T064915Z

content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date
334d016f755cd6dc58c53a86e183882f8ec14f52fb05345887c8a5edd42c87b7

string_to_sign:
AWS4-HMAC-SHA256
20180403T064915Z
20180403//s3/aws4_request
3da91a42ec560683e543665a0bc890c9f035e779cda705c066061cf16aade0ae

signature:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

s3.PUT /testkey
DEBUG: 183c SSL connect: s3.my.local.endpoint.de:443...
DEBUG: 183c TCP connect: s3.my.local.endpoint.de:443...
DEBUG: 183c 🔗  New:            ⏸    0↑     0↓    s3.my.local.endpoint.de:443:0 ≣16 RawFD(43)
DEBUG: 183c 👁  Start write:T0  ⏸    0↑     0↓    s3.my.local.endpoint.de:443:0 ≣16 RawFD(43)
➡️   "PUT /mybucket/testkey HTTP/1.1\r\n"
➡️   "Content-MD5: lS0sVtBIWVgzZ0e83ZhZDQ==\r\n"
➡️   "Host: s3.my.local.endpoint.de\r\n"
➡️   "Content-Type: application/octet-stream\r\n"
➡️   "Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXX/20180403//s3/aws4_request, SignedHeaders=content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n"
➡️   "x-amz-date: 20180403T064915Z\r\n"
➡️   "User-Agent: AWSCore.jl/0.0.0\r\n"
➡️   "x-amz-content-sha256: 334d016f755cd6dc58c53a86e183882f8ec14f52fb05345887c8a5edd42c87b7\r\n"
➡️   "Content-Length: 6\r\n"
➡️   "\r\n"
DEBUG: 183c 👁  Start read: T0  ⏸    0↑🔒    0↓    s3.my.local.endpoint.de:443:0 ≣16 RawFD(43)
➡️   "Hello!"
DEBUG: 183c ❗️  ConnectionLayer EOFError(). Closing: T0  💀    0↑🔒    0↓🔒   s3.my.local.endpoint.de:443:0 ≣16 inactive 59.9s RawFD(-1)
DEBUG: 183c 🗣  Write done: T0  💀    1↑     0↓🔒   s3.my.local.endpoint.de:443:0 ≣16 inactive 59.9s RawFD(-1)
DEBUG: 183c ✉️  Read done:  T0  💀    1↑     1↓    s3.my.local.endpoint.de:443:0 ≣16 RawFD(-1)
DEBUG: 183c 🗑  Deleted:        💀    1↑     1↓    s3.my.local.endpoint.de:443:0 ≣16 RawFD(-1)

# [... repetition of above block for three times ...]

ERROR: IOError(EOFError() during request(https://s3.my.local.endpoint.de/mybucket/testkey))
```

**Comment by samoconnor** [comment] 2018-04-03 10:39
There are 10 commits between v0.6.5 and v0.6.6: https://github.com/JuliaWeb/HTTP.jl/compare/v0.6.5...v0.6.6
I suspect this line: https://github.com/JuliaWeb/HTTP.jl/commit/b602c4ea0cf346b35ae9bea13db2c960eee759de#diff-9d9dbf32fde891ae74761647fbf8e2a4L50

This change was made to allow the response-reading task to begin before the request body-sending task. This is desirable in the case where the server sends an error response immediately after receiving the headers; and in order to avoid sending a non-idempotent request body on a failed connection ([detail here](https://github.com/JuliaWeb/HTTP.jl/commit/b602c4ea0cf346b35ae9bea13db2c960eee759de)).

My best guess is that in your case the tiny delay introduced between sending the request headers and the request body is causing the connection to be closed by the server. Is there some kind of proxy (or firewall or load balancer or reverse proxy or transparent proxy or similar) between you and the server? I have heard of cases where request fragmentation can cause connections to be dropped by proxies.

Please update HTTP.jl to v0.6.8 and edit `HTTP.jl/src/StreamRequest.jl` and try adding `yield()` after line 56:
```julia
            if iofunction == nothing
                @async writebody(http, request, body)
             👉 yield() 
                startread(http)
                readbody(http, response, response_stream)
            else
```
https://github.com/JuliaWeb/HTTP.jl/blob/master/src/StreamRequest.jl#L55-L59

Also, I'm assuming that your local "S3 endpoint" is a 3rd party S3 emulation like (Minio or similar).
It would be useful if you could describe what S3 implementation your endpoint is running and what (if any) proxies are between you and it.

**Comment by mcsage** [comment] 2018-04-04 07:05
Indeed we are using Ceph (RasdosGW) S3 API http://docs.ceph.com/docs/master/radosgw/s3/
Our proxy is a nginx. Pretty basic config is in place.
```   
 location /{
        client_max_body_size 0;
        proxy_set_header        Host $host;
        proxy_pass_request_headers on;
        proxy_pass              http://ceph-radosgw;
        access_log      /var/log/nginx/ceph-s3.access.log;
        error_log       /var/log/nginx/ceph-s3.error.log;
    }
```
I guess it's the nginx conf because the connection is killed there (http 408 RequestTimeout) even before reaching the s3 radosgw.

**Comment by samoconnor** [comment] 2018-04-16 06:58
@mcsage, thanks for the info, I tried a few quick local tests using nginx, but I couldn't reproduce the issue. 

@akubisch, I've made a commit to HTTP.jl to revert the v0.6.6 change that I suspect might be causing the problem: https://github.com/JuliaWeb/HTTP.jl/commit/fa6b20617ef2c0ee68e2415d348c04839a792e4e
Can you please try latest `master` of HTTP.jl and let me know if this cures the problem?

**Comment by akubisch** [comment] 2018-04-16 07:10
Just tried it and it does indeed cure the problem :-)

**Comment by samoconnor** [comment] 2018-04-16 07:13
Thanks Alexander.
I'll tag a new version of HTTP and close this issue.

**Closed by samoconnor** 2018-04-16 07:13 UTC

**Comment by samoconnor** [comment] 2018-04-16 07:27
https://github.com/JuliaWeb/HTTP.jl/releases/tag/v0.6.9
